[[plugins]]
# HTMLやCSSの構文を簡単に記述できる
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
# HTML5のシンタックスハイライト
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
# Lessのシンタックスハイライト
repo = 'groenewege/vim-less'
on_ft = ['less']

[[plugins]]
# CSSの色を表示
repo = 'ap/vim-css-color'
on_ft = ['css', 'less', 'sass']

[[plugins]]
# JavaScriptのインデンテーション
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
# CoffeeScriptのシンタックスハイライト
repo = 'kchmck/vim-coffee-script'
on_path = ['.*\.coffee']
on_ft = ['coffee']

[[plugins]]
# Slimのシンタックスハイライトとインデンテーション
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
# Pug(旧Jade)のシンタックスハイライトとインデンテーション
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'jade']

[[plugins]]
# Markdownのシンタックスハイライト
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_source = ''' " {{{
    " 自動で折りたたまないようにする
    let g:vim_markdown_folding_disabled = 1
''' # }}}

[[plugins]]
# Markdownのプレビュー
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_source = ''' " {{{
    " リアルタイムプレビューを有効化
    let g:previm_enable_realtime = 1
''' # }}}

[[plugins]]
# Scalaのシンタックスハイライト
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
# Swiftのシンタックスハイライト
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
# Haskellのシンタックスハイライトとインデンテーション
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = ''' " {{{
    let g:haskell_conceal = 0
    let g:haskell_conceal_enumerations = 0
''' # }}}

[[plugins]]
# HaskellのためのNeocomplecacheを使った自動補完
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']
hook_add = ''' " {{{
    setlocal omnifunc=necoghc#omnifunc
''' # }}}

[[plugins]]
# Go言語の統合サポート
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = ''' " {{{
    " GoFmtコマンドを保存時に走らせる
    augroup GoFmtVimGoCommands
        autocmd!
        autocmd BufWritePre *.go GoFmt
    augroup END
''' # }}}

[[plugins]]
# LLVM IRのシンタックスハイライト
repo = 'qnighy/llvm.vim'
on_ft = ['llvm']

[[plugins]]
# Arduinoのシンタックスハイライト
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']

[[plugins]]
# TOMLのシンタックスハイライト
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
# Excelファイルのプレビュー
repo = 'demmys/excelview-vim'
depends = ['webapi-vim']
on_path = ['.*\.xlsx']
on_cmd = ['ExcelView']
hook_source = ''' " {{{
    " Excelファイルをexcelview-vimで開く
    augroup ExcelviewVimOpenExcel
        autocmd!
        autocmd BufReadCmd *.xlsx silent bdelete | execute 'ExcelView' expand("<afile>")
    augroup END
''' # }}}

[[plugins]]
# Kotlinのシンタックスハイライト
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']
